language: php

php:
  - 5.6

env:
  - DATABASE_URL=postgres://postgres

services: postgres

before_script:
  - composer install --dev --prefer-source
  - test doctrine:database:create
  - test doctrine:schema:load

script: phpunit
