<?php

namespace ChopShopper\Entity;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends \Doctrine\ORM\EntityRepository
{
    public function findIngredientByName($name)
    {
        return $this->_em->findOneBy(array('name' => $name));
    }
}
