<?php

    namespace ChopShopper\Entity;

    use Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException;

    /**
     * RecipeRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class RecipeRepository extends \Doctrine\ORM\EntityRepository
    {
        public function createRecipe($recipe_json, $persist=true)
        {
            $ob = json_decode($recipe_json);

            if ($ob === null)
            {
                throw new NotAcceptableHttpException('Invalid Object');
            }

            $ret = new Recipe();

            try
            {
                $ret->loadFromJson($recipe_json);
            }
            catch(Exception $e)
            {
               throw new NotAcceptableHttpException("Invalid Object", $e, 405);
            }

            return $ret;
        }
    }
