<?php

namespace ChopShopper\Entity;

/**
 * RecipeStepIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeStepIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
